---
title: "CRC datasets MDS"
output:
  html_document:
    df_print: paged
---
```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = 'CRC_MDS_plots/', dev = c('png','svg'), warning = FALSE)
library(tidyverse)
library(magrittr)
library(vegan)
library(RColorBrewer)

```


```{r load_data}
mpa_table <- read_tsv("METAPHLAN3_CRC_DATA.tsv", col_names = FALSE, skip = 42) %>% 
  column_to_rownames("X1") %>% 
  t() %>% 
  as.data.frame()

metadata <- read_tsv("METAPHLAN3_CRC_DATA.tsv", col_names = FALSE, n_max = 42) %>% 
  t() %>% 
  as.data.frame(row.names = FALSE, stringsAsFactors=FALSE) %>% 
  column_to_rownames(var = 'V2')
colnames(metadata) <- as.character(metadata[1,])
metadata <- metadata[-1,] 
rownames(mpa_table) <- rownames(metadata)
```


```{r calculate MDS}
mds_res_norm <- cmdscale(vegdist(sinh(sqrt(mpa_table)), method = 'bray', diag = TRUE, upper = FALSE))
mds_res_nonorm <- cmdscale(vegdist(mpa_table, method = 'bray', diag = TRUE, upper = FALSE))
```

```{r CRC_MDS_no_normalization, fig.width=10, fig.height=6, fig.retina=TRUE}
mds_res_nonorm %>% 
  as.data.frame() %>% 
  rownames_to_column('sampleID') %>% 
  left_join(metadata %>%  rownames_to_column('sampleID')) %>% 
  select(sampleID, MDS1=V1, MDS2=V2, study_condition, dataset_name) %>% 
ggplot() +
  geom_point(aes(MDS1,MDS2, shape=study_condition, color=dataset_name), size=2) +
  scale_color_manual(values = c("#0039A6","#FF6319","#6CBE45","#996633","#A7A9AC","#FCCC0A","#808183","#EE352E","#00933C","#B933AD"), name = 'Dataset') +
  theme_minimal(base_size = 15) + 
  scale_shape_discrete(name = 'Condition')
```


```{r CRC_MDS_sinh_sqrt_normalization,  fig.width=10, fig.height=6, fig.retina=TRUE}
mds_res_norm %>% 
  as.data.frame() %>% 
  rownames_to_column('sampleID') %>% 
  left_join(metadata %>%  rownames_to_column('sampleID')) %>% 
  select(sampleID, MDS1=V1, MDS2=V2, study_condition, dataset_name) %>% 
  ggplot() +
  geom_point(aes(MDS1,MDS2, shape=study_condition, color=dataset_name), size=2) +
  scale_color_manual(values = c("#0039A6","#FF6319","#6CBE45","#996633","#A7A9AC","#FCCC0A","#808183","#EE352E","#00933C","#B933AD"), name = 'Dataset') +
  theme_minimal(base_size = 15) +
  scale_shape_discrete(name = 'Condition')
```